apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  trafficManagement:
    components:
      # The default profile is tuned to fit on smaller clusters. Increase the requests and HPA
      # a bit to ensure we can handle larger scale clusters.
      pilot:
        k8s:
          resources:
            requests:
              cpu: 2000m

  gateways:
    components:
      # Egress is supported but not default
      egressGateway:
        enabled: false

  # Policy is not supported
  policy:
    enabled: false

  # Telemetry here refers to mixer telemetry. We will enable telemetry v2 instead
  telemetry:
    enabled: false

  values:
    # Protocol sniffing is not supported
    pilot:
      enableProtocolSniffingForOutbound: false
      enableProtocolSniffingForInbound: false

    # Grafana is disabled by default, but supported with --set values.grafana.enabled=true
    # This requires enabling prometheus.
    grafana:
      enabled: false

    # Prometheus is disabled by default, but supported with --set values.prometheus.enabled=true
    prometheus:
      enabled: false

    # Enable SDS on ingress
    gateways:
      istio-ingressgateway:
        sds:
          enabled: true

    # Enable telemetry v2 backend by Prometheus.
    telemetry:
      enabled: true
      v1:
        enabled: false
      v2:
        enabled: true
        prometheus:
          enabled: true
        stackdriver:
          enabled: false

    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true

    global:
      proxy:
        # Protocol detection timeout is not supported
        protocolDetectionTimeout: 0s

      # Locality load balancing is not supported
      localityLbSetting:
        enabled: false

      # Enable permissive mTLS by default
      mtls:
        enabled: false
